# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file_transfer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x66ile_transfer.proto\"!\n\x0f\x46ileUploadChunk\x12\x0e\n\x06\x62uffer\x18\x01 \x01(\x0c\"U\n\x12\x46ileUploadResponse\x12!\n\x06status\x18\x01 \x01(\x0e\x32\x11.FileUploadStatus\x12\x12\n\x05\x65rror\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x08\n\x06_error*\x94\x01\n\x10\x46ileUploadStatus\x12\x17\n\x13\x46ILE_UPLOAD_UNKNOWN\x10\x00\x12\x17\n\x13\x46ILE_UPLOAD_SUCCESS\x10\x01\x12\x15\n\x11\x46ILE_UPLOAD_ERROR\x10\x02\x12\x1c\n\x18\x41\x43\x43OUNT_STATUS_SUSPENDED\x10\x03\x12\x19\n\x15\x41\x43\x43OUNT_STATUS_CLOSED\x10\x04\x32J\n\x13\x46ileTransferService\x12\x33\n\x06Upload\x12\x10.FileUploadChunk\x1a\x13.FileUploadResponse\"\x00(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_transfer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_FILEUPLOADSTATUS']._serialized_start=146
  _globals['_FILEUPLOADSTATUS']._serialized_end=294
  _globals['_FILEUPLOADCHUNK']._serialized_start=23
  _globals['_FILEUPLOADCHUNK']._serialized_end=56
  _globals['_FILEUPLOADRESPONSE']._serialized_start=58
  _globals['_FILEUPLOADRESPONSE']._serialized_end=143
  _globals['_FILETRANSFERSERVICE']._serialized_start=296
  _globals['_FILETRANSFERSERVICE']._serialized_end=370
# @@protoc_insertion_point(module_scope)
